root = "."
tmp_dir = "tmp"

[build]
# cmd = "go build -o ./tmp/knownme ./cmd/knownme && lsof -ti:6420 | xargs kill -9 2>/dev/null || true"
# entrypoint = ["./tmp/knownme", "browser", "--restart", "--dev", "--port", "6420", "--no-open"]
cmd = "lsof -ti:6420 | xargs kill -9 2>/dev/null || true"
entrypoint = ["go","run","./cmd/knownme/main.go", "browser", "--restart", "--dev", "--port", "6420", "--no-open"]
include_ext = ["go"]
exclude_dir = ["tmp", "bin", "ui", "node_modules", ".git", ".known-me"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[misc]
clean_on_exit = true
